version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'  
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    volumes:
      - ./mongodb/data:/data/db  
      - ./mongodb/config:/data/configdb  